### ISSUE TITLE
Plugin crashes when no time entries exist

### ISSUE THREAD

**Issue by RoqueRehrmann** [JamesNZL/flow-toggl-plugin#7]
Today i ran into the following issue. I use a fresh toggl account with no time-entries. After creating an entry via the web UI, the plugin works as expected. Thanks for the plugin.

Date: 05/16/2023 21:38:07
Exception:
Toggl Track Exception: 
Websites: https://github.com/JamesNZL/flow-toggl-plugin
Author: JamesNZL
Version: 2.1.5
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Sequence contains no elements
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Flow.Launcher.Plugin.TogglTrack.TogglTrack.RequestStartEntry(CancellationToken token, Query query)
   at Flow.Launcher.Plugin.TogglTrack.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by JamesNZL** [comment]
Reproduced, thanks!
Fixed in [`v2.1.6`](https://github.com/JamesNZL/flow-toggl-plugin/releases/tag/v2.1.6).

A star would be appreciated if you find the plugin useful :)
